// 20211013122158
// https://www.birdables.com/api/cards

[
  {
    "id": "zb4r6ooujoflqi",
    "slug": "brown-pelican",
    "bigName": "Pelican",
    "rarity": 1,
    "location": "North America",
    "smallName": "Brown",
    "accentColor": "F29600",
    "scientificName": "Pelecanus occidentalis",
    "birdName": "Brown Pelican",
    "friendlyId": "brown-pelican_01",
    "etsyId": "1074673261",
    "releaseDate": "2021-08-30T00:00:00.000Z",
    "eBird": "brnpel",
    "audubon": "brown-pelican"
  },
  {
    "id": "3pkscx65hnigbc",
    "slug": "yellow-warbler",
    "bigName": "Warbler",
    "rarity": 2,
    "location": "North America",
    "smallName": "Yellow",
    "accentColor": "FED519",
    "scientificName": "Setophaga petechia",
    "birdName": "Yellow Warbler",
    "friendlyId": "yellow-warbler_01",
    "etsyId": "1074712259",
    "releaseDate": "2021-08-30T00:00:00.000Z",
    "specialty": true,
    "eBird": "yelwar",
    "audubon": "yellow-warbler"
  },
  {
    "id": "fzsez5zs1tbrnn",
    "slug": "northern-cardinal",
    "bigName": "Cardinal",
    "rarity": 1,
    "location": "North America",
    "smallName": "Northern",
    "accentColor": "E42020",
    "scientificName": "Cardinalis cardinalis",
    "birdName": "Northern Cardinal",
    "friendlyId": "northern-cardinal_01",
    "etsyId": "1074707501",
    "releaseDate": "2021-08-30T00:00:00.000Z",
    "specialty": true,
    "eBird": "norcar",
    "audubon": "northern-cardinal"
  },
  {
    "id": "mxoevnhakpefm9",
    "slug": "blue-jay",
    "bigName": "Jay",
    "rarity": 1,
    "location": "North America",
    "smallName": "Blue",
    "accentColor": "0594FD",
    "scientificName": "Cyanocitta cristata",
    "birdName": "Blue Jay",
    "friendlyId": "blue-jay_01",
    "etsyId": "1060748840",
    "releaseDate": "2021-08-30T00:00:00.000Z",
    "eBird": "blujay",
    "audubon": "blue-jay"
  },
  {
    "id": "skynylkgbw74o3",
    "slug": "roseate-spoonbill",
    "bigName": "Spoonbill",
    "rarity": 3,
    "location": "North America",
    "smallName": "Roseate",
    "accentColor": "FD93AA",
    "scientificName": "Platalea ajaja",
    "birdName": "Roseate Spoonbill",
    "friendlyId": "roseate-spoonbill_01",
    "etsyId": "1060757158",
    "releaseDate": "2021-08-30T00:00:00.000Z",
    "specialty": true,
    "eBird": "rosspo1",
    "audubon": "roseate-spoonbill"
  },
  {
    "id": "lbyuf6ofapq2ks",
    "slug": "pileated-woodpecker",
    "bigName": "Woodpecker",
    "rarity": 2,
    "location": "North America",
    "smallName": "Pileated",
    "accentColor": "FD0605",
    "scientificName": "Dryocopus pileatus",
    "birdName": "Pileated Woodpecker",
    "friendlyId": "pileated-woodpecker_01",
    "etsyId": "1060756244",
    "releaseDate": "2021-08-30T02:30:00.000Z",
    "eBird": "pilwoo",
    "audubon": "pileated-woodpecker"
  },
  {
    "id": "pcsp5b230hefrf",
    "slug": "sandhill-crane",
    "bigName": "Crane",
    "rarity": 3,
    "location": "North America",
    "smallName": "Sandhill",
    "accentColor": "CD040B",
    "scientificName": "Antigone canadensis",
    "birdName": "Sandhill Crane",
    "friendlyId": "sandhill-crane_01",
    "etsyId": "1074710879",
    "releaseDate": "2021-08-30T00:00:00.000Z",
    "specialty": true,
    "eBird": "sancra",
    "audubon": "sandhill-crane"
  },
  {
    "id": "1sl78lrqrc0tiq",
    "slug": "california-condor",
    "bigName": "Condor",
    "rarity": 5,
    "location": "North America",
    "smallName": "California",
    "accentColor": "FD9731",
    "scientificName": "Gymnogyps californianus",
    "birdName": "California Condor",
    "friendlyId": "california-condor_01",
    "etsyId": "1060749764",
    "releaseDate": "2021-08-30T00:00:00.000Z",
    "specialty": true,
    "eBird": "calcon",
    "audubon": "california-condor"
  },
  {
    "id": "frebrbaib3vaoo",
    "slug": "java-sparrow",
    "bigName": "Sparrow",
    "rarity": 4,
    "location": "North America",
    "smallName": "Java",
    "accentColor": "FD6F4E",
    "scientificName": "Lonchura oryzivora",
    "birdName": "Java Sparrow",
    "friendlyId": "java-sparrow_01",
    "etsyId": "1074706519",
    "releaseDate": "2021-08-30T00:30:00.000Z",
    "specialty": true,
    "eBird": "javspa"
  },
  {
    "id": "imk9d6jmfqcl9i",
    "slug": "atlantic-puffin",
    "bigName": "Puffin",
    "rarity": 4,
    "location": "North America",
    "smallName": "Atlantic",
    "accentColor": "FF5B1E",
    "scientificName": "Fratercula arctica",
    "birdName": "Atlantic Puffin",
    "friendlyId": "atlantic-puffin_01",
    "etsyId": "1060747348",
    "openseaUrl": "123",
    "releaseDate": "2021-08-30T00:00:00.000Z",
    "specialty": true,
    "eBird": "atlpuf",
    "audubon": "atlantic-puffin"
  },
  {
    "id": "alc9fvegh2glot",
    "slug": "osprey",
    "bigName": "Osprey",
    "rarity": 2,
    "location": "North America",
    "accentColor": "CCA87C",
    "scientificName": "Pandion haliaetus",
    "birdName": "Osprey",
    "friendlyId": "osprey_01",
    "etsyId": "1074708035",
    "releaseDate": "2021-08-30T00:00:00.000Z",
    "eBird": "osprey",
    "audubon": "osprey"
  },
  {
    "id": "xzdfsi1oix9ebg",
    "slug": "wood-stork",
    "bigName": "Stork",
    "rarity": 3,
    "location": "North America",
    "smallName": "Wood",
    "accentColor": "98A2A8",
    "scientificName": "Mycteria americana",
    "birdName": "Wood Stork",
    "friendlyId": "wood-stork_01",
    "etsyId": "1074711867",
    "releaseDate": "2021-08-30T00:00:00.000Z",
    "eBird": "woosto",
    "audubon": "wood-stork"
  },
  {
    "id": "onlmylmg17h0ys",
    "slug": "belted-kingfisher",
    "bigName": "Kingfisher",
    "rarity": 2,
    "location": "North America",
    "smallName": "Belted",
    "accentColor": "637B84",
    "scientificName": "Megaceryle alcyon",
    "birdName": "Belted Kingfisher",
    "friendlyId": "belted-kingfisher_01",
    "etsyId": "1074701753",
    "releaseDate": "2021-08-30T00:00:00.000Z",
    "eBird": "belkin1",
    "audubon": "belted-kingfisher"
  },
  {
    "id": "f0wdlmkmamfeoh",
    "slug": "bluethroat",
    "bigName": "Bluethroat",
    "rarity": 3,
    "location": "North America",
    "accentColor": "5571B2",
    "scientificName": "Luscinia svecica",
    "birdName": "Bluethroat",
    "friendlyId": "bluethroat_01",
    "etsyId": "1074702575",
    "releaseDate": "2021-08-30T00:00:00.000Z",
    "eBird": "blueth",
    "audubon": "bluethroat"
  },
  {
    "id": "2lj3ajov7uds67",
    "slug": "brown-thrasher",
    "bigName": "Thrasher",
    "rarity": 1,
    "location": "North America",
    "smallName": "Brown",
    "accentColor": "D26322",
    "scientificName": "Toxostoma rufum",
    "birdName": "Brown Thrasher",
    "friendlyId": "brown-thrasher_01",
    "etsyId": "1074705085",
    "releaseDate": "2021-08-30T00:00:00.000Z",
    "eBird": "brnthr",
    "audubon": "brown-thrasher"
  },
  {
    "id": "asl1jbx75ojwgg",
    "slug": "cedar-waxwing",
    "bigName": "Waxwing",
    "rarity": 1,
    "location": "North America",
    "smallName": "Cedar",
    "accentColor": "F9D205",
    "scientificName": "Bombycilla cedrorum",
    "birdName": "Cedar Waxwing",
    "friendlyId": "cedar-waxwing_01",
    "etsyId": "1060752298",
    "releaseDate": "2021-08-30T05:00:00.000Z",
    "eBird": "cedwax",
    "audubon": "cedar-waxwing"
  },
  {
    "id": "7gt1lduiv00gpr",
    "slug": "eastern-towhee",
    "bigName": "Towhee",
    "rarity": 2,
    "location": "North America",
    "smallName": "Eastern",
    "accentColor": "FD8418",
    "scientificName": "Pipilo erythrophthalmus",
    "birdName": "Eastern Towhee",
    "friendlyId": "eastern-towhee_01",
    "etsyId": "1060752766",
    "releaseDate": "2021-08-30T00:00:00.000Z",
    "eBird": "eastow",
    "audubon": "eastern-towhee"
  },
  {
    "id": "zwygkyfaaczuva",
    "slug": "loggerhead-shrike",
    "bigName": "Shrike",
    "rarity": 2,
    "location": "North America",
    "smallName": "Loggerhead",
    "accentColor": "8F8F8F",
    "scientificName": "Lanius ludovicianus",
    "birdName": "Loggerhead Shrike",
    "friendlyId": "loggerhead-shrike_01",
    "etsyId": "1074707023",
    "releaseDate": "2021-08-30T02:00:00.000Z",
    "eBird": "logshr",
    "audubon": "loggerhead-shrike"
  },
  {
    "id": "xg1tqmm8jhe1jh",
    "slug": "piping-plover",
    "bigName": "Plover",
    "rarity": 3,
    "location": "North America",
    "smallName": "Piping",
    "accentColor": "FF920D",
    "scientificName": "Charadrius melodus",
    "birdName": "Piping Plover",
    "friendlyId": "piping-plover_01",
    "etsyId": "1060756702",
    "releaseDate": "2021-08-30T00:00:00.000Z",
    "eBird": "pipplo",
    "audubon": "piping-plover"
  },
  {
    "id": "0lyoy8kwkkvn89",
    "slug": "snowy-owl",
    "bigName": "Owl",
    "rarity": 4,
    "location": "North America",
    "smallName": "Snowy",
    "accentColor": "F8C204",
    "scientificName": "Bubo scandiacus",
    "birdName": "Snowy Owl",
    "friendlyId": "snowy-owl_01",
    "etsyId": "1074711351",
    "releaseDate": "2021-08-29T00:00:00.000Z",
    "eBird": "snoowl1",
    "audubon": "snowy-owl"
  }
]